### ISSUE TITLE
Cargo workspaces that reference multiple versions of a contained package can confuse `cargo-maelstrom`

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#427]
I'm going to use the `cargo-mutants` repo as an example. The repo has two packages: `cargo-mutants` and `mutants`. The top-level `Cargo.toml` specifies both a `[package]`, for `cargo-mutants`, and a `[workspace]`, which contains `mutants` (in the `mutants_attrs` directory).

```toml
[package]
name = "cargo-mutants"
version = "24.11.0"

# [snip]

[dependencies]
anyhow = "1.0.86"
# [snip]
mutants = "0.0.3"

# [snip]

[workspace]
members = ["mutants_attrs"]
resolver = "2"

# [snip]
```

The `mutants_attrs`'s `Cargo.toml` looks like this:
```toml
[package]
name = "mutants"
version = "0.0.3"
edition = "2018"
license = "MIT"
description = "Decorator attributes to be used with cargo-mutants"
repository = "https://github.com/sourcefrog/cargo-mutants"
categories = ["development-tools::testing"]

[lib]
proc-macro = true
```

The problem here is that `cargo` thinks there are two versions of the `mutants` package. One of them is the regular dependency specified in the top-level `Cargo.toml`. The other is the one specified in the `mutants_attrs` package. If you just limit the tests to one of these packages or another, using `--include='package.eq(mutants)'`, or `--include='package.eq(cargo-mutants)`', for example, things work fine. However, if you specify both of them together, `cargo` gets confused and gives an error:
```
neal-desktop:~/git/cargo-mutants[101]% cargo "test" "--no-run" "--message-format=json-render-diagnostics" "--color=always" "--package" "cargo-mutants@24.11.0" "--package" "mutants@0.0.3"
error: There are multiple `mutants` packages in your project, and the specification `mutants@0.0.3` is ambiguous.
Please re-run this command with one of the following specifications:
  path+file:///home/neal/git/cargo-mutants/mutants_attrs#mutants@0.0.3
  registry+https://github.com/rust-lang/crates.io-index#mutants@0.0.3
neal-desktop:~/git/cargo-mutants[101]%
```

The fix in this particular case is to change the top-level `Cargo.toml` like so:
```toml
[dependencies]
mutants = { version = "0.0.3", path = "mutants_attr" }
```

It's unclear to me what we should do about this problem. I think we have a few options:
- Do nothing in `cargo-maelstrom`. Instead, document this particular issue and tell people how to fix it.
- Detect this issue in `cargo-maelstrom` and give some good diagnostics.
- Do the collection on a package-by-package basis.
